[package]
name = "madara"
version.workspace = true
edition.workspace = true

[dependencies]
aes.workspace = true
aidoku = { workspace = true, features = ["json"] }
base64.workspace = true
block-padding.workspace = true
cbc = { workspace = true, features = ["alloc"] }
chrono = { workspace = true, features = ["alloc"] }
digest.workspace = true
md-5.workspace = true
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
