[package]
name = "guya"
version.workspace = true
edition.workspace = true

[dependencies]
aidoku = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive", "alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
