[package]
name = "mangadex"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { workspace = true, features = ["json"] }
chrono = { workspace = true, features = ["alloc"] }
hashbrown.workspace = true
regex = { workspace = true, features = ["unicode-perl"] }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
