[package]
name = "mangathemesia"
version.workspace = true
edition.workspace = true

[dependencies]
aidoku = { workspace = true, features = ["json"] }
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
