[package]
name = "mangareader"
version.workspace = true
edition.workspace = true

[dependencies]
aidoku = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test", "json"] }
aidoku-test.workspace = true
