[package]
name = "mangago"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aes.workspace = true
aidoku.workspace = true
base64.workspace = true
cbc = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
