[package]
name = "violetscans"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku.workspace = true
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
