[package]
name = "manhuagui"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { workspace = true, features = ["json"] }
regex = { workspace = true, features = ["unicode"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
