[package]
name = "copymanga"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aes.workspace = true
aidoku = { workspace = true, features = ["json"] }
cbc.workspace = true
chinese-number.workspace = true
hex.workspace = true
regex = { workspace = true, features = ["unicode"] }
serde.workspace = true
serde_json.workspace = true
spin.workspace = true
strum.workspace = true
uuid = { workspace = true, features = ["serde"] }
