[package]
name = "spoilerplus"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive", "alloc"] }
wpcomics.workspace = true

[dev-dependencies]
aidoku = { workspace = true, features = ["test", "json"] }
aidoku-test.workspace = true
