[package]
name = "mangarawbest"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aes-gcm.workspace = true
aidoku = { workspace = true, features = ["json"] }
base64.workspace = true
hmac.workspace = true
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }
sha2.workspace = true

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
