[package]
name = "godamanga"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { workspace = true, features = ["helpers", "json"] }
chrono = { workspace = true, features = ["serde"] }
regex = { workspace = true, features = ["unicode"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
