[package]
name = "remanga"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { workspace = true, features = ["json"] }
chrono = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive", "alloc"] }

[dev-dependencies]
aidoku = { workspace = true, features = ["test"] }
aidoku-test.workspace = true
